// Golf Majors — all-time winners
// Source: hand-authored in the design handoff (masters/project/src/data.js)
// Ported verbatim to TypeScript.

export type MajorKey = 'masters' | 'pga' | 'usopen' | 'open';

export interface Major {
  key: MajorKey;
  name: string;
  short: string;
  start: number;
  venue: string;
  loc: string;
  founded: number;
  org: string;
  month: string;
  monthIdx: number;
  color: string;
}

export type WinnerRow = [year: number, pkey: string, score: string | null, venue?: string, note?: string];

export interface Win {
  major: MajorKey;
  year: number;
  pkey: string;
  score: string | null;
  venue: string;
  note: string;
}

export interface Player {
  name: string;
  country: string;
  era: string;
}

export interface PlayerStats {
  pkey: string;
  masters: number;
  pga: number;
  usopen: number;
  open: number;
  total: number;
  wins: Win[];
}

export const MAJORS: Major[] = [
  { key: 'masters',  name: 'The Masters',         short: 'Masters',  start: 1934, venue: 'Augusta National Golf Club', loc: 'Augusta, GA', founded: 1934, org: 'Augusta National', month: 'April',   monthIdx: 3,  color: '#D4A017' },
  { key: 'pga',      name: 'PGA Championship',    short: 'PGA',      start: 1916, venue: 'Various Courses',            loc: 'USA',         founded: 1916, org: 'PGA of America', month: 'May',     monthIdx: 4,  color: '#B31B1B' },
  { key: 'usopen',   name: 'U.S. Open',           short: 'US Open',  start: 1895, venue: 'Various Courses',            loc: 'USA',         founded: 1895, org: 'USGA',           month: 'June',    monthIdx: 5,  color: '#1E4DB7' },
  { key: 'open',     name: 'The Open Championship', short: 'The Open', start: 1860, venue: 'Various Links Courses',    loc: 'UK',          founded: 1860, org: 'The R&A',        month: 'July',    monthIdx: 6,  color: '#5E3A8A' },
];

// Winners arrays: [year, playerKey, scoreToPar?, venue?, notes?]
// scoreToPar uses "-18" / "+1" / "E"; null = pre-par era

export const WINNERS: Record<MajorKey, WinnerRow[]> = {
  masters: [
    [1934,'horton-smith','-4','Augusta National'],
    [1935,'gene-sarazen','-6','Augusta National','Playoff v. Craig Wood'],
    [1936,'horton-smith','-3','Augusta National'],
    [1937,'byron-nelson','-5','Augusta National'],
    [1938,'henry-picard','-3','Augusta National'],
    [1939,'ralph-guldahl','-9','Augusta National'],
    [1940,'jimmy-demaret','-8','Augusta National'],
    [1941,'craig-wood','-8','Augusta National'],
    [1942,'byron-nelson','-8','Augusta National','Playoff v. Hogan'],
    [1946,'herman-keiser','-6','Augusta National'],
    [1947,'jimmy-demaret','-7','Augusta National'],
    [1948,'claude-harmon','-9','Augusta National'],
    [1949,'sam-snead','-6','Augusta National'],
    [1950,'jimmy-demaret','-5','Augusta National'],
    [1951,'ben-hogan','-8','Augusta National'],
    [1952,'sam-snead','-2','Augusta National'],
    [1953,'ben-hogan','-14','Augusta National'],
    [1954,'sam-snead','-1','Augusta National','Playoff v. Hogan'],
    [1955,'cary-middlecoff','-9','Augusta National'],
    [1956,'jack-burke','+1','Augusta National'],
    [1957,'doug-ford','-5','Augusta National'],
    [1958,'arnold-palmer','-4','Augusta National'],
    [1959,'art-wall','-4','Augusta National'],
    [1960,'arnold-palmer','-6','Augusta National'],
    [1961,'gary-player','-8','Augusta National'],
    [1962,'arnold-palmer','-8','Augusta National','Playoff'],
    [1963,'jack-nicklaus','-2','Augusta National'],
    [1964,'arnold-palmer','-12','Augusta National'],
    [1965,'jack-nicklaus','-17','Augusta National'],
    [1966,'jack-nicklaus','E','Augusta National','Playoff'],
    [1967,'gay-brewer','-8','Augusta National'],
    [1968,'bob-goalby','-11','Augusta National'],
    [1969,'george-archer','-7','Augusta National'],
    [1970,'billy-casper','-9','Augusta National','Playoff'],
    [1971,'charles-coody','-9','Augusta National'],
    [1972,'jack-nicklaus','-2','Augusta National'],
    [1973,'tommy-aaron','-5','Augusta National'],
    [1974,'gary-player','-10','Augusta National'],
    [1975,'jack-nicklaus','-12','Augusta National'],
    [1976,'raymond-floyd','-17','Augusta National'],
    [1977,'tom-watson','-12','Augusta National'],
    [1978,'gary-player','-11','Augusta National'],
    [1979,'fuzzy-zoeller','-8','Augusta National','Playoff'],
    [1980,'seve-ballesteros','-13','Augusta National'],
    [1981,'tom-watson','-8','Augusta National'],
    [1982,'craig-stadler','-4','Augusta National','Playoff'],
    [1983,'seve-ballesteros','-8','Augusta National'],
    [1984,'ben-crenshaw','-11','Augusta National'],
    [1985,'bernhard-langer','-6','Augusta National'],
    [1986,'jack-nicklaus','-9','Augusta National','Age 46'],
    [1987,'larry-mize','-3','Augusta National','Playoff'],
    [1988,'sandy-lyle','-7','Augusta National'],
    [1989,'nick-faldo','-5','Augusta National','Playoff'],
    [1990,'nick-faldo','-10','Augusta National','Playoff'],
    [1991,'ian-woosnam','-11','Augusta National'],
    [1992,'fred-couples','-13','Augusta National'],
    [1993,'bernhard-langer','-11','Augusta National'],
    [1994,'jose-maria-olazabal','-9','Augusta National'],
    [1995,'ben-crenshaw','-14','Augusta National'],
    [1996,'nick-faldo','-12','Augusta National'],
    [1997,'tiger-woods','-18','Augusta National','Record −18; age 21'],
    [1998,'mark-omeara','-9','Augusta National'],
    [1999,'jose-maria-olazabal','-8','Augusta National'],
    [2000,'vijay-singh','-10','Augusta National'],
    [2001,'tiger-woods','-16','Augusta National','Tiger Slam'],
    [2002,'tiger-woods','-12','Augusta National'],
    [2003,'mike-weir','-7','Augusta National','Playoff'],
    [2004,'phil-mickelson','-9','Augusta National'],
    [2005,'tiger-woods','-12','Augusta National','Playoff; chip-in on 16'],
    [2006,'phil-mickelson','-7','Augusta National'],
    [2007,'zach-johnson','+1','Augusta National'],
    [2008,'trevor-immelman','-8','Augusta National'],
    [2009,'angel-cabrera','-12','Augusta National','Playoff'],
    [2010,'phil-mickelson','-16','Augusta National'],
    [2011,'charl-schwartzel','-14','Augusta National'],
    [2012,'bubba-watson','-10','Augusta National','Playoff'],
    [2013,'adam-scott','-9','Augusta National','Playoff; first Australian'],
    [2014,'bubba-watson','-8','Augusta National'],
    [2015,'jordan-spieth','-18','Augusta National','Tied record'],
    [2016,'danny-willett','-5','Augusta National'],
    [2017,'sergio-garcia','-9','Augusta National','Playoff'],
    [2018,'patrick-reed','-15','Augusta National'],
    [2019,'tiger-woods','-13','Augusta National','11-year gap'],
    [2020,'dustin-johnson','-20','Augusta National','Record; played in November'],
    [2021,'hideki-matsuyama','-10','Augusta National','First Japanese man'],
    [2022,'scottie-scheffler','-10','Augusta National'],
    [2023,'jon-rahm','-12','Augusta National'],
    [2024,'scottie-scheffler','-11','Augusta National'],
    [2025,'rory-mcilroy','-11','Augusta National','Playoff; career Grand Slam'],
    [2026,'rory-mcilroy','-14','Augusta National','Back-to-back green jackets'],
  ],

  pga: [
    [1916,'jim-barnes',null,'Siwanoy'],
    [1919,'jim-barnes',null,'Engineers'],
    [1920,'jock-hutchison',null,'Flossmoor'],
    [1921,'walter-hagen',null,'Inwood'],
    [1922,'gene-sarazen',null,'Oakmont'],
    [1923,'gene-sarazen',null,'Pelham'],
    [1924,'walter-hagen',null,'French Lick'],
    [1925,'walter-hagen',null,'Olympia Fields'],
    [1926,'walter-hagen',null,'Salisbury'],
    [1927,'walter-hagen',null,'Cedar Crest'],
    [1928,'leo-diegel',null,'Five Farms'],
    [1929,'leo-diegel',null,'Hillcrest'],
    [1930,'tommy-armour',null,'Fresh Meadow'],
    [1931,'tom-creavy',null,'Wannamoisett'],
    [1932,'olin-dutra',null,'Keller'],
    [1933,'gene-sarazen',null,'Blue Mound'],
    [1934,'paul-runyan',null,'Park CC'],
    [1935,'johnny-revolta',null,'Twin Hills'],
    [1936,'denny-shute',null,'Pinehurst'],
    [1937,'denny-shute',null,'Pittsburgh FC'],
    [1938,'paul-runyan',null,'Shawnee'],
    [1939,'henry-picard',null,'Pomonok'],
    [1940,'byron-nelson',null,'Hershey'],
    [1941,'vic-ghezzi',null,'Cherry Hills'],
    [1942,'sam-snead',null,'Seaview'],
    [1944,'bob-hamilton',null,'Manito'],
    [1945,'byron-nelson',null,'Moraine'],
    [1946,'ben-hogan',null,'Portland'],
    [1947,'jim-ferrier',null,'Plum Hollow'],
    [1948,'ben-hogan',null,'Norwood Hills'],
    [1949,'sam-snead',null,'Hermitage'],
    [1950,'chandler-harper',null,'Scioto'],
    [1951,'sam-snead',null,'Oakmont'],
    [1952,'jim-turnesa',null,'Big Spring'],
    [1953,'walter-burkemo',null,'Birmingham'],
    [1954,'chick-harbert',null,'Keller'],
    [1955,'doug-ford',null,'Meadowbrook'],
    [1956,'jack-burke',null,'Blue Hill'],
    [1957,'lionel-hebert',null,'Miami Valley'],
    [1958,'dow-finsterwald','-4','Llanerch'],
    [1959,'bob-rosburg','-3','Minneapolis'],
    [1960,'jay-hebert','-9','Firestone'],
    [1961,'jerry-barber','-3','Olympia Fields','Playoff'],
    [1962,'gary-player','-12','Aronimink'],
    [1963,'jack-nicklaus','-5','Dallas AC'],
    [1964,'bobby-nichols','-9','Columbus CC'],
    [1965,'dave-marr','-2','Laurel Valley'],
    [1966,'al-geiberger','-8','Firestone'],
    [1967,'don-january','-9','Columbine','Playoff'],
    [1968,'julius-boros','+1','Pecan Valley'],
    [1969,'raymond-floyd','-8','NCR'],
    [1970,'dave-stockton','-1','Southern Hills'],
    [1971,'jack-nicklaus','-7','PGA National'],
    [1972,'gary-player','+1','Oakland Hills'],
    [1973,'jack-nicklaus','-7','Canterbury'],
    [1974,'lee-trevino','-8','Tanglewood'],
    [1975,'jack-nicklaus','-4','Firestone'],
    [1976,'dave-stockton','+1','Congressional'],
    [1977,'lanny-wadkins','-6','Pebble Beach','Playoff'],
    [1978,'john-mahaffey','-8','Oakmont','Playoff'],
    [1979,'david-graham','-8','Oakland Hills','Playoff'],
    [1980,'jack-nicklaus','-6','Oak Hill'],
    [1981,'larry-nelson','-7','Atlanta AC'],
    [1982,'raymond-floyd','-8','Southern Hills'],
    [1983,'hal-sutton','-10','Riviera'],
    [1984,'lee-trevino','-15','Shoal Creek'],
    [1985,'hubert-green','-6','Cherry Hills'],
    [1986,'bob-tway','-8','Inverness','Bunker hole-out on 18'],
    [1987,'larry-nelson','+1','PGA National','Playoff'],
    [1988,'jeff-sluman','-12','Oak Tree'],
    [1989,'payne-stewart','-12','Kemper Lakes'],
    [1990,'wayne-grady','-6','Shoal Creek'],
    [1991,'john-daly','-12','Crooked Stick','9th alternate'],
    [1992,'nick-price','-6','Bellerive'],
    [1993,'paul-azinger','-12','Inverness','Playoff'],
    [1994,'nick-price','-11','Southern Hills'],
    [1995,'steve-elkington','-17','Riviera','Playoff'],
    [1996,'mark-brooks','-11','Valhalla','Playoff'],
    [1997,'davis-love','-11','Winged Foot'],
    [1998,'vijay-singh','-9','Sahalee'],
    [1999,'tiger-woods','-11','Medinah'],
    [2000,'tiger-woods','-18','Valhalla','Playoff v. May'],
    [2001,'david-toms','-15','Atlanta AC'],
    [2002,'rich-beem','-10','Hazeltine'],
    [2003,'shaun-micheel','-4','Oak Hill'],
    [2004,'vijay-singh','-8','Whistling Straits','Playoff'],
    [2005,'phil-mickelson','-4','Baltusrol'],
    [2006,'tiger-woods','-18','Medinah'],
    [2007,'tiger-woods','-8','Southern Hills'],
    [2008,'padraig-harrington','-3','Oakland Hills'],
    [2009,'yang-yongeun','-8','Hazeltine','First Asian man'],
    [2010,'martin-kaymer','-11','Whistling Straits','Playoff'],
    [2011,'keegan-bradley','-8','Atlanta AC','Playoff'],
    [2012,'rory-mcilroy','-13','Kiawah Island','Record 8-stroke win'],
    [2013,'jason-dufner','-10','Oak Hill'],
    [2014,'rory-mcilroy','-16','Valhalla'],
    [2015,'jason-day','-20','Whistling Straits','Record'],
    [2016,'jimmy-walker','-14','Baltusrol'],
    [2017,'justin-thomas','-8','Quail Hollow'],
    [2018,'brooks-koepka','-16','Bellerive'],
    [2019,'brooks-koepka','-8','Bethpage Black'],
    [2020,'collin-morikawa','-13','TPC Harding Park'],
    [2021,'phil-mickelson','-6','Kiawah Island','Oldest major winner (50)'],
    [2022,'justin-thomas','-5','Southern Hills','Playoff'],
    [2023,'brooks-koepka','-9','Oak Hill'],
    [2024,'xander-schauffele','-21','Valhalla','Record'],
    [2025,'scottie-scheffler','-11','Quail Hollow'],
  ],

  usopen: [
    [1895,'horace-rawlins',null,'Newport'],
    [1896,'james-foulis',null,'Shinnecock'],
    [1897,'joe-lloyd',null,'Chicago'],
    [1898,'fred-herd',null,'Myopia'],
    [1899,'willie-smith',null,'Baltimore'],
    [1900,'harry-vardon',null,'Chicago'],
    [1901,'willie-anderson',null,'Myopia'],
    [1902,'laurie-auchterlonie',null,'Garden City'],
    [1903,'willie-anderson',null,'Baltusrol'],
    [1904,'willie-anderson',null,'Glen View'],
    [1905,'willie-anderson',null,'Myopia'],
    [1906,'alex-smith',null,'Onwentsia'],
    [1907,'alec-ross',null,'Philadelphia Cricket'],
    [1908,'fred-mcleod',null,'Myopia'],
    [1909,'george-sargent',null,'Englewood'],
    [1910,'alex-smith',null,'Philadelphia Cricket'],
    [1911,'john-mcdermott',null,'Chicago'],
    [1912,'john-mcdermott',null,'CC Buffalo'],
    [1913,'francis-ouimet',null,'Brookline','Amateur; playoff v. Vardon & Ray'],
    [1914,'walter-hagen',null,'Midlothian'],
    [1915,'jerome-travers',null,'Baltusrol','Amateur'],
    [1916,'chick-evans',null,'Minikahda','Amateur'],
    [1919,'walter-hagen',null,'Brae Burn'],
    [1920,'ted-ray',null,'Inverness'],
    [1921,'jim-barnes',null,'Columbia'],
    [1922,'gene-sarazen',null,'Skokie'],
    [1923,'bobby-jones',null,'Inwood'],
    [1924,'cyril-walker',null,'Oakland Hills'],
    [1925,'willie-macfarlane',null,'Worcester'],
    [1926,'bobby-jones',null,'Scioto'],
    [1927,'tommy-armour',null,'Oakmont'],
    [1928,'johnny-farrell',null,'Olympia Fields'],
    [1929,'bobby-jones',null,'Winged Foot'],
    [1930,'bobby-jones',null,'Interlachen','Grand Slam year'],
    [1931,'billy-burke',null,'Inverness'],
    [1932,'gene-sarazen',null,'Fresh Meadow'],
    [1933,'johnny-goodman',null,'North Shore','Amateur'],
    [1934,'olin-dutra',null,'Merion'],
    [1935,'sam-parks',null,'Oakmont'],
    [1936,'tony-manero',null,'Baltusrol'],
    [1937,'ralph-guldahl',null,'Oakland Hills'],
    [1938,'ralph-guldahl',null,'Cherry Hills'],
    [1939,'byron-nelson',null,'Philadelphia'],
    [1940,'lawson-little',null,'Canterbury'],
    [1941,'craig-wood',null,'Colonial'],
    [1946,'lloyd-mangrum',null,'Canterbury'],
    [1947,'lew-worsham',null,'St. Louis'],
    [1948,'ben-hogan',null,'Riviera'],
    [1950,'ben-hogan',null,'Merion','Playoff; post-accident'],
    [1951,'ben-hogan',null,'Oakland Hills'],
    [1952,'julius-boros',null,'Northwood'],
    [1953,'ben-hogan',null,'Oakmont'],
    [1954,'ed-furgol',null,'Baltusrol'],
    [1955,'jack-fleck',null,'Olympic','Playoff v. Hogan'],
    [1956,'cary-middlecoff',null,'Oak Hill'],
    [1957,'dick-mayer',null,'Inverness'],
    [1958,'tommy-bolt',null,'Southern Hills'],
    [1959,'billy-casper','-2','Winged Foot'],
    [1960,'arnold-palmer','-4','Cherry Hills','Final-round 65'],
    [1961,'gene-littler','+1','Oakland Hills'],
    [1962,'jack-nicklaus','-1','Oakmont','Playoff v. Palmer; pro debut'],
    [1963,'julius-boros','+9','Brookline','Playoff'],
    [1964,'ken-venturi','-2','Congressional'],
    [1965,'gary-player','+2','Bellerive','Playoff'],
    [1966,'billy-casper','-2','Olympic','Playoff v. Palmer'],
    [1967,'jack-nicklaus','-5','Baltusrol'],
    [1968,'lee-trevino','-5','Oak Hill'],
    [1969,'orville-moody','+1','Champions'],
    [1970,'tony-jacklin','-7','Hazeltine'],
    [1971,'lee-trevino','E','Merion','Playoff v. Nicklaus'],
    [1972,'jack-nicklaus','+2','Pebble Beach'],
    [1973,'johnny-miller','-5','Oakmont','Final-round 63'],
    [1974,'hale-irwin','+7','Winged Foot','Massacre'],
    [1975,'lou-graham','+3','Medinah','Playoff'],
    [1976,'jerry-pate','-2','Atlanta AC'],
    [1977,'hubert-green','-2','Southern Hills'],
    [1978,'andy-north','+1','Cherry Hills'],
    [1979,'hale-irwin','E','Inverness'],
    [1980,'jack-nicklaus','-8','Baltusrol'],
    [1981,'david-graham','-7','Merion'],
    [1982,'tom-watson','-6','Pebble Beach','Chip-in on 17'],
    [1983,'larry-nelson','-4','Oakmont'],
    [1984,'fuzzy-zoeller','-4','Winged Foot','Playoff'],
    [1985,'andy-north','-1','Oakland Hills'],
    [1986,'raymond-floyd','-1','Shinnecock'],
    [1987,'scott-simpson','-3','Olympic'],
    [1988,'curtis-strange','-6','Brookline','Playoff'],
    [1989,'curtis-strange','+2','Oak Hill','Back-to-back'],
    [1990,'hale-irwin','-8','Medinah','Playoff; age 45'],
    [1991,'payne-stewart','-6','Hazeltine','Playoff'],
    [1992,'tom-kite','-3','Pebble Beach'],
    [1993,'lee-janzen','-8','Baltusrol'],
    [1994,'ernie-els','-5','Oakmont','Playoff'],
    [1995,'corey-pavin','E','Shinnecock'],
    [1996,'steve-jones','-2','Oakland Hills'],
    [1997,'ernie-els','-4','Congressional'],
    [1998,'lee-janzen','E','Olympic'],
    [1999,'payne-stewart','-1','Pinehurst','Final-hole putt'],
    [2000,'tiger-woods','-12','Pebble Beach','15-stroke win'],
    [2001,'retief-goosen','-4','Southern Hills','Playoff'],
    [2002,'tiger-woods','-3','Bethpage Black'],
    [2003,'jim-furyk','-8','Olympia Fields'],
    [2004,'retief-goosen','-4','Shinnecock'],
    [2005,'michael-campbell','E','Pinehurst'],
    [2006,'geoff-ogilvy','+5','Winged Foot'],
    [2007,'angel-cabrera','+5','Oakmont'],
    [2008,'tiger-woods','-1','Torrey Pines','Playoff; broken leg'],
    [2009,'lucas-glover','-4','Bethpage Black'],
    [2010,'graeme-mcdowell','E','Pebble Beach'],
    [2011,'rory-mcilroy','-16','Congressional','Record'],
    [2012,'webb-simpson','+1','Olympic'],
    [2013,'justin-rose','+1','Merion'],
    [2014,'martin-kaymer','-9','Pinehurst'],
    [2015,'jordan-spieth','-5','Chambers Bay'],
    [2016,'dustin-johnson','-4','Oakmont'],
    [2017,'brooks-koepka','-16','Erin Hills'],
    [2018,'brooks-koepka','+1','Shinnecock','Back-to-back'],
    [2019,'gary-woodland','-13','Pebble Beach'],
    [2020,'bryson-dechambeau','-6','Winged Foot'],
    [2021,'jon-rahm','-6','Torrey Pines'],
    [2022,'matt-fitzpatrick','-6','Brookline'],
    [2023,'wyndham-clark','-10','LA Country Club'],
    [2024,'bryson-dechambeau','-6','Pinehurst'],
    [2025,'jj-spaun','-1','Oakmont'],
  ],

  open: [
    [1860,'willie-park-sr',null,'Prestwick'],
    [1861,'tom-morris-sr',null,'Prestwick'],
    [1862,'tom-morris-sr',null,'Prestwick'],
    [1863,'willie-park-sr',null,'Prestwick'],
    [1864,'tom-morris-sr',null,'Prestwick'],
    [1865,'andrew-strath',null,'Prestwick'],
    [1866,'willie-park-sr',null,'Prestwick'],
    [1867,'tom-morris-sr',null,'Prestwick'],
    [1868,'tom-morris-jr',null,'Prestwick'],
    [1869,'tom-morris-jr',null,'Prestwick'],
    [1870,'tom-morris-jr',null,'Prestwick'],
    [1872,'tom-morris-jr',null,'Prestwick'],
    [1873,'tom-kidd',null,'St Andrews'],
    [1874,'mungo-park',null,'Musselburgh'],
    [1875,'willie-park-sr',null,'Prestwick'],
    [1876,'bob-martin',null,'St Andrews'],
    [1877,'jamie-anderson',null,'Musselburgh'],
    [1878,'jamie-anderson',null,'Prestwick'],
    [1879,'jamie-anderson',null,'St Andrews'],
    [1880,'bob-ferguson',null,'Musselburgh'],
    [1881,'bob-ferguson',null,'Prestwick'],
    [1882,'bob-ferguson',null,'St Andrews'],
    [1883,'willie-fernie',null,'Musselburgh'],
    [1884,'jack-simpson',null,'Prestwick'],
    [1885,'bob-martin',null,'St Andrews'],
    [1886,'david-brown',null,'Musselburgh'],
    [1887,'willie-park-jr',null,'Prestwick'],
    [1888,'jack-burns',null,'St Andrews'],
    [1889,'willie-park-jr',null,'Musselburgh'],
    [1890,'john-ball',null,'Prestwick','Amateur'],
    [1891,'hugh-kirkaldy',null,'St Andrews'],
    [1892,'harold-hilton',null,'Muirfield','Amateur'],
    [1893,'willie-auchterlonie',null,'Prestwick'],
    [1894,'jh-taylor',null,'Sandwich'],
    [1895,'jh-taylor',null,'St Andrews'],
    [1896,'harry-vardon',null,'Muirfield'],
    [1897,'harold-hilton',null,'Hoylake'],
    [1898,'harry-vardon',null,'Prestwick'],
    [1899,'harry-vardon',null,'Sandwich'],
    [1900,'jh-taylor',null,'St Andrews'],
    [1901,'james-braid',null,'Muirfield'],
    [1902,'sandy-herd',null,'Hoylake'],
    [1903,'harry-vardon',null,'Prestwick'],
    [1904,'jack-white',null,'Sandwich'],
    [1905,'james-braid',null,'St Andrews'],
    [1906,'james-braid',null,'Muirfield'],
    [1907,'arnaud-massy',null,'Hoylake','First non-British'],
    [1908,'james-braid',null,'Prestwick'],
    [1909,'jh-taylor',null,'Deal'],
    [1910,'james-braid',null,'St Andrews'],
    [1911,'harry-vardon',null,'Sandwich'],
    [1912,'ted-ray',null,'Muirfield'],
    [1913,'jh-taylor',null,'Hoylake'],
    [1914,'harry-vardon',null,'Prestwick','Record 6th'],
    [1920,'george-duncan',null,'Deal'],
    [1921,'jock-hutchison',null,'St Andrews'],
    [1922,'walter-hagen',null,'Sandwich'],
    [1923,'arthur-havers',null,'Troon'],
    [1924,'walter-hagen',null,'Hoylake'],
    [1925,'jim-barnes',null,'Prestwick'],
    [1926,'bobby-jones',null,'Lytham'],
    [1927,'bobby-jones',null,'St Andrews'],
    [1928,'walter-hagen',null,'Sandwich'],
    [1929,'walter-hagen',null,'Muirfield'],
    [1930,'bobby-jones',null,'Hoylake','Grand Slam year'],
    [1931,'tommy-armour',null,'Carnoustie'],
    [1932,'gene-sarazen',null,'Prince\u2019s'],
    [1933,'denny-shute',null,'St Andrews'],
    [1934,'henry-cotton',null,'Sandwich'],
    [1935,'alf-perry',null,'Muirfield'],
    [1936,'alf-padgham',null,'Hoylake'],
    [1937,'henry-cotton',null,'Carnoustie'],
    [1938,'reg-whitcombe',null,'Sandwich'],
    [1939,'dick-burton',null,'St Andrews'],
    [1946,'sam-snead',null,'St Andrews'],
    [1947,'fred-daly',null,'Hoylake'],
    [1948,'henry-cotton',null,'Muirfield'],
    [1949,'bobby-locke',null,'Sandwich'],
    [1950,'bobby-locke',null,'Troon'],
    [1951,'max-faulkner',null,'Portrush'],
    [1952,'bobby-locke',null,'Lytham'],
    [1953,'ben-hogan',null,'Carnoustie','Triple Crown year'],
    [1954,'peter-thomson',null,'Birkdale'],
    [1955,'peter-thomson',null,'St Andrews'],
    [1956,'peter-thomson',null,'Hoylake'],
    [1957,'bobby-locke',null,'St Andrews'],
    [1958,'peter-thomson',null,'Lytham'],
    [1959,'gary-player',null,'Muirfield'],
    [1960,'kel-nagle','-2','St Andrews'],
    [1961,'arnold-palmer','-4','Birkdale'],
    [1962,'arnold-palmer','-12','Troon'],
    [1963,'bob-charles','-3','Lytham','Playoff; first lefty'],
    [1964,'tony-lema','-9','St Andrews'],
    [1965,'peter-thomson','-3','Birkdale'],
    [1966,'jack-nicklaus','-2','Muirfield'],
    [1967,'roberto-devicenzo','-10','Hoylake'],
    [1968,'gary-player','+1','Carnoustie'],
    [1969,'tony-jacklin','-4','Lytham'],
    [1970,'jack-nicklaus','-5','St Andrews','Playoff'],
    [1971,'lee-trevino','-14','Birkdale'],
    [1972,'lee-trevino','-6','Muirfield'],
    [1973,'tom-weiskopf','-12','Troon'],
    [1974,'gary-player','-2','Lytham'],
    [1975,'tom-watson','-9','Carnoustie','Playoff'],
    [1976,'johnny-miller','-9','Birkdale'],
    [1977,'tom-watson','-12','Turnberry','Duel in the Sun'],
    [1978,'jack-nicklaus','-7','St Andrews'],
    [1979,'seve-ballesteros','-1','Lytham'],
    [1980,'tom-watson','-13','Muirfield'],
    [1981,'bill-rogers','-4','Sandwich'],
    [1982,'tom-watson','-4','Troon'],
    [1983,'tom-watson','-9','Birkdale'],
    [1984,'seve-ballesteros','-12','St Andrews'],
    [1985,'sandy-lyle','+2','Sandwich'],
    [1986,'greg-norman','E','Turnberry'],
    [1987,'nick-faldo','-5','Muirfield'],
    [1988,'seve-ballesteros','-11','Lytham'],
    [1989,'mark-calcavecchia','-13','Troon','Playoff'],
    [1990,'nick-faldo','-18','St Andrews'],
    [1991,'ian-baker-finch','-8','Birkdale'],
    [1992,'nick-faldo','-12','Muirfield'],
    [1993,'greg-norman','-13','Sandwich'],
    [1994,'nick-price','-12','Turnberry'],
    [1995,'john-daly','-6','St Andrews','Playoff'],
    [1996,'tom-lehman','-13','Lytham'],
    [1997,'justin-leonard','-12','Troon'],
    [1998,'mark-omeara','E','Birkdale','Playoff'],
    [1999,'paul-lawrie','+6','Carnoustie','Van de Velde playoff'],
    [2000,'tiger-woods','-19','St Andrews','Record'],
    [2001,'david-duval','-10','Lytham'],
    [2002,'ernie-els','-6','Muirfield','Playoff'],
    [2003,'ben-curtis','-1','Sandwich'],
    [2004,'todd-hamilton','-10','Troon','Playoff'],
    [2005,'tiger-woods','-14','St Andrews'],
    [2006,'tiger-woods','-18','Hoylake'],
    [2007,'padraig-harrington','-7','Carnoustie','Playoff'],
    [2008,'padraig-harrington','+3','Birkdale'],
    [2009,'stewart-cink','-2','Turnberry','Playoff v. Watson'],
    [2010,'louis-oosthuizen','-16','St Andrews'],
    [2011,'darren-clarke','-5','Sandwich'],
    [2012,'ernie-els','-7','Lytham'],
    [2013,'phil-mickelson','-3','Muirfield'],
    [2014,'rory-mcilroy','-17','Hoylake'],
    [2015,'zach-johnson','-15','St Andrews','Playoff'],
    [2016,'henrik-stenson','-20','Troon','Record'],
    [2017,'jordan-spieth','-12','Birkdale'],
    [2018,'francesco-molinari','-8','Carnoustie'],
    [2019,'shane-lowry','-15','Portrush'],
    [2021,'collin-morikawa','-15','Sandwich'],
    [2022,'cameron-smith','-20','St Andrews','Record tie'],
    [2023,'brian-harman','-13','Hoylake'],
    [2024,'xander-schauffele','-9','Troon'],
    [2025,'scottie-scheffler','-17','Portrush'],
  ],
};

// Player metadata — name, country (ISO code), notable style
export const PLAYERS: Record<string, Player> = {
  // Top winners / key figures (others auto-fill from key)
  'jack-nicklaus':      { name: 'Jack Nicklaus',       country: 'US', era: '1960s–80s' },
  'tiger-woods':        { name: 'Tiger Woods',         country: 'US', era: '1997–2019' },
  'walter-hagen':       { name: 'Walter Hagen',        country: 'US', era: '1910s–30s' },
  'ben-hogan':          { name: 'Ben Hogan',           country: 'US', era: '1940s–50s' },
  'gary-player':        { name: 'Gary Player',         country: 'ZA', era: '1950s–70s' },
  'tom-watson':         { name: 'Tom Watson',          country: 'US', era: '1970s–80s' },
  'harry-vardon':       { name: 'Harry Vardon',        country: 'GB', era: '1890s–1910s' },
  'bobby-jones':        { name: 'Bobby Jones',         country: 'US', era: '1920s–30s' },
  'gene-sarazen':       { name: 'Gene Sarazen',        country: 'US', era: '1920s–30s' },
  'sam-snead':          { name: 'Sam Snead',           country: 'US', era: '1940s–50s' },
  'arnold-palmer':      { name: 'Arnold Palmer',       country: 'US', era: '1950s–60s' },
  'phil-mickelson':     { name: 'Phil Mickelson',      country: 'US', era: '2004–2021' },
  'rory-mcilroy':       { name: 'Rory McIlroy',        country: 'GB', era: '2011–' },
  'seve-ballesteros':   { name: 'Seve Ballesteros',    country: 'ES', era: '1979–1988' },
  'nick-faldo':         { name: 'Nick Faldo',          country: 'GB', era: '1987–1996' },
  'peter-thomson':      { name: 'Peter Thomson',       country: 'AU', era: '1950s–60s' },
  'bobby-locke':        { name: 'Bobby Locke',         country: 'ZA', era: '1940s–50s' },
  'james-braid':        { name: 'James Braid',         country: 'GB', era: '1900s–10s' },
  'jh-taylor':          { name: 'J.H. Taylor',         country: 'GB', era: '1890s–1910s' },
  'tom-morris-jr':      { name: 'Tom Morris Jr.',      country: 'GB', era: '1868–1872' },
  'tom-morris-sr':      { name: 'Old Tom Morris',      country: 'GB', era: '1861–1867' },
  'willie-park-sr':     { name: 'Willie Park Sr.',     country: 'GB', era: '1860–1875' },
  'brooks-koepka':      { name: 'Brooks Koepka',       country: 'US', era: '2017–2023' },
  'scottie-scheffler':  { name: 'Scottie Scheffler',   country: 'US', era: '2022–' },
  'jordan-spieth':      { name: 'Jordan Spieth',       country: 'US', era: '2015–2017' },
  'dustin-johnson':     { name: 'Dustin Johnson',      country: 'US', era: '2016–2020' },
  'jon-rahm':           { name: 'Jon Rahm',            country: 'ES', era: '2021–2023' },
  'xander-schauffele':  { name: 'Xander Schauffele',   country: 'US', era: '2024–' },
  'collin-morikawa':    { name: 'Collin Morikawa',     country: 'US', era: '2020–2021' },
  'padraig-harrington': { name: 'Pádraig Harrington',  country: 'IE', era: '2007–2008' },
  'ernie-els':          { name: 'Ernie Els',           country: 'ZA', era: '1994–2012' },
  'vijay-singh':        { name: 'Vijay Singh',         country: 'FJ', era: '1998–2004' },
  'hale-irwin':         { name: 'Hale Irwin',          country: 'US', era: '1974–1990' },
  'lee-trevino':        { name: 'Lee Trevino',         country: 'US', era: '1968–1984' },
  'raymond-floyd':      { name: 'Raymond Floyd',       country: 'US', era: '1969–1986' },
  'byron-nelson':       { name: 'Byron Nelson',        country: 'US', era: '1937–1945' },
  'jim-barnes':         { name: 'Jim Barnes',          country: 'GB', era: '1916–1925' },
  'jamie-anderson':     { name: 'Jamie Anderson',      country: 'GB', era: '1877–1879' },
  'bob-ferguson':       { name: 'Bob Ferguson',        country: 'GB', era: '1880–1882' },
  'willie-anderson':    { name: 'Willie Anderson',     country: 'GB', era: '1901–1905' },
  'greg-norman':        { name: 'Greg Norman',         country: 'AU', era: '1986–1993' },
  'nick-price':         { name: 'Nick Price',          country: 'ZW', era: '1992–1994' },
  'henry-cotton':       { name: 'Henry Cotton',        country: 'GB', era: '1934–1948' },
  'ralph-guldahl':      { name: 'Ralph Guldahl',       country: 'US', era: '1937–1939' },
  'jimmy-demaret':      { name: 'Jimmy Demaret',       country: 'US', era: '1940–1950' },
  'billy-casper':       { name: 'Billy Casper',        country: 'US', era: '1959–1970' },
  'cary-middlecoff':    { name: 'Cary Middlecoff',     country: 'US', era: '1949–1956' },
  'paul-runyan':        { name: 'Paul Runyan',         country: 'US', era: '1934–1938' },
  'denny-shute':        { name: 'Denny Shute',         country: 'US', era: '1933–1937' },
  'leo-diegel':         { name: 'Leo Diegel',          country: 'US', era: '1928–1929' },
  'mark-omeara':        { name: 'Mark O\u2019Meara',   country: 'US', era: '1998' },
  'jason-day':          { name: 'Jason Day',           country: 'AU', era: '2015' },
  'adam-scott':         { name: 'Adam Scott',          country: 'AU', era: '2013' },
  'hideki-matsuyama':   { name: 'Hideki Matsuyama',    country: 'JP', era: '2021' },
  'yang-yongeun':       { name: 'Y.E. Yang',           country: 'KR', era: '2009' },
  'bernhard-langer':    { name: 'Bernhard Langer',     country: 'DE', era: '1985–1993' },
  'jose-maria-olazabal':{ name: 'José María Olazábal', country: 'ES', era: '1994–1999' },
  'sandy-lyle':         { name: 'Sandy Lyle',          country: 'GB', era: '1985–1988' },
  'ian-woosnam':        { name: 'Ian Woosnam',         country: 'GB', era: '1991' },
  'fred-couples':       { name: 'Fred Couples',        country: 'US', era: '1992' },
  'ben-crenshaw':       { name: 'Ben Crenshaw',        country: 'US', era: '1984–1995' },
  'payne-stewart':      { name: 'Payne Stewart',       country: 'US', era: '1989–1999' },
  'curtis-strange':     { name: 'Curtis Strange',      country: 'US', era: '1988–1989' },
  'retief-goosen':      { name: 'Retief Goosen',       country: 'ZA', era: '2001–2004' },
  'angel-cabrera':      { name: 'Ángel Cabrera',       country: 'AR', era: '2007–2009' },
  'martin-kaymer':      { name: 'Martin Kaymer',       country: 'DE', era: '2010–2014' },
  'bubba-watson':       { name: 'Bubba Watson',        country: 'US', era: '2012–2014' },
  'zach-johnson':       { name: 'Zach Johnson',        country: 'US', era: '2007–2015' },
  'louis-oosthuizen':   { name: 'Louis Oosthuizen',    country: 'ZA', era: '2010' },
  'darren-clarke':      { name: 'Darren Clarke',       country: 'GB', era: '2011' },
  'henrik-stenson':     { name: 'Henrik Stenson',      country: 'SE', era: '2016' },
  'francesco-molinari': { name: 'Francesco Molinari',  country: 'IT', era: '2018' },
  'shane-lowry':        { name: 'Shane Lowry',         country: 'IE', era: '2019' },
  'cameron-smith':      { name: 'Cameron Smith',       country: 'AU', era: '2022' },
  'brian-harman':       { name: 'Brian Harman',        country: 'US', era: '2023' },
  'sergio-garcia':      { name: 'Sergio Garcia',       country: 'ES', era: '2017' },
  'patrick-reed':       { name: 'Patrick Reed',        country: 'US', era: '2018' },
  'danny-willett':      { name: 'Danny Willett',       country: 'GB', era: '2016' },
  'charl-schwartzel':   { name: 'Charl Schwartzel',    country: 'ZA', era: '2011' },
  'trevor-immelman':    { name: 'Trevor Immelman',     country: 'ZA', era: '2008' },
  'mike-weir':          { name: 'Mike Weir',           country: 'CA', era: '2003' },
  'wyndham-clark':      { name: 'Wyndham Clark',       country: 'US', era: '2023' },
  'matt-fitzpatrick':   { name: 'Matt Fitzpatrick',    country: 'GB', era: '2022' },
  'bryson-dechambeau':  { name: 'Bryson DeChambeau',   country: 'US', era: '2020–2024' },
  'gary-woodland':      { name: 'Gary Woodland',       country: 'US', era: '2019' },
  'justin-rose':        { name: 'Justin Rose',         country: 'GB', era: '2013' },
  'webb-simpson':       { name: 'Webb Simpson',        country: 'US', era: '2012' },
  'graeme-mcdowell':    { name: 'Graeme McDowell',     country: 'GB', era: '2010' },
  'lucas-glover':       { name: 'Lucas Glover',        country: 'US', era: '2009' },
  'geoff-ogilvy':       { name: 'Geoff Ogilvy',        country: 'AU', era: '2006' },
  'michael-campbell':   { name: 'Michael Campbell',    country: 'NZ', era: '2005' },
  'jim-furyk':          { name: 'Jim Furyk',           country: 'US', era: '2003' },
  'justin-thomas':      { name: 'Justin Thomas',       country: 'US', era: '2017–2022' },
  'jason-dufner':       { name: 'Jason Dufner',        country: 'US', era: '2013' },
  'keegan-bradley':     { name: 'Keegan Bradley',      country: 'US', era: '2011' },
  'jimmy-walker':       { name: 'Jimmy Walker',        country: 'US', era: '2016' },
  'david-toms':         { name: 'David Toms',          country: 'US', era: '2001' },
  'rich-beem':          { name: 'Rich Beem',           country: 'US', era: '2002' },
  'shaun-micheel':      { name: 'Shaun Micheel',       country: 'US', era: '2003' },
  'jj-spaun':           { name: 'J.J. Spaun',          country: 'US', era: '2025' },
  'tony-jacklin':       { name: 'Tony Jacklin',        country: 'GB', era: '1969–1970' },
  'bob-charles':        { name: 'Bob Charles',         country: 'NZ', era: '1963' },
  'roberto-devicenzo':  { name: 'Roberto De Vicenzo',  country: 'AR', era: '1967' },
  'kel-nagle':          { name: 'Kel Nagle',           country: 'AU', era: '1960' },
  'david-graham':       { name: 'David Graham',        country: 'AU', era: '1979–1981' },
  'ian-baker-finch':    { name: 'Ian Baker-Finch',     country: 'AU', era: '1991' },
  'mark-calcavecchia':  { name: 'Mark Calcavecchia',   country: 'US', era: '1989' },
  'tom-lehman':         { name: 'Tom Lehman',          country: 'US', era: '1996' },
  'justin-leonard':     { name: 'Justin Leonard',      country: 'US', era: '1997' },
  'paul-lawrie':        { name: 'Paul Lawrie',         country: 'GB', era: '1999' },
  'david-duval':        { name: 'David Duval',         country: 'US', era: '2001' },
  'ben-curtis':         { name: 'Ben Curtis',          country: 'US', era: '2003' },
  'todd-hamilton':      { name: 'Todd Hamilton',       country: 'US', era: '2004' },
  'stewart-cink':       { name: 'Stewart Cink',        country: 'US', era: '2009' },
  'johnny-miller':      { name: 'Johnny Miller',       country: 'US', era: '1973–1976' },
  'tom-weiskopf':       { name: 'Tom Weiskopf',        country: 'US', era: '1973' },
  'larry-nelson':       { name: 'Larry Nelson',        country: 'US', era: '1981–1987' },
  'john-daly':          { name: 'John Daly',           country: 'US', era: '1991–1995' },
  'paul-azinger':       { name: 'Paul Azinger',        country: 'US', era: '1993' },
  'steve-elkington':    { name: 'Steve Elkington',     country: 'AU', era: '1995' },
  'mark-brooks':        { name: 'Mark Brooks',         country: 'US', era: '1996' },
  'davis-love':         { name: 'Davis Love III',      country: 'US', era: '1997' },
  'hal-sutton':         { name: 'Hal Sutton',          country: 'US', era: '1983' },
  'hubert-green':       { name: 'Hubert Green',        country: 'US', era: '1977–1985' },
  'bob-tway':           { name: 'Bob Tway',            country: 'US', era: '1986' },
  'jeff-sluman':        { name: 'Jeff Sluman',         country: 'US', era: '1988' },
  'wayne-grady':        { name: 'Wayne Grady',         country: 'AU', era: '1990' },
  'jerry-barber':       { name: 'Jerry Barber',        country: 'US', era: '1961' },
  'bobby-nichols':      { name: 'Bobby Nichols',       country: 'US', era: '1964' },
  'dave-marr':          { name: 'Dave Marr',           country: 'US', era: '1965' },
  'al-geiberger':       { name: 'Al Geiberger',        country: 'US', era: '1966' },
  'don-january':        { name: 'Don January',         country: 'US', era: '1967' },
  'julius-boros':       { name: 'Julius Boros',        country: 'US', era: '1952–1968' },
  'dave-stockton':      { name: 'Dave Stockton',       country: 'US', era: '1970–1976' },
  'lanny-wadkins':      { name: 'Lanny Wadkins',       country: 'US', era: '1977' },
  'john-mahaffey':      { name: 'John Mahaffey',       country: 'US', era: '1978' },
  'fuzzy-zoeller':      { name: 'Fuzzy Zoeller',       country: 'US', era: '1979–1984' },
  'craig-stadler':      { name: 'Craig Stadler',       country: 'US', era: '1982' },
  'larry-mize':         { name: 'Larry Mize',          country: 'US', era: '1987' },
  'horton-smith':       { name: 'Horton Smith',        country: 'US', era: '1934–1936' },
  'henry-picard':       { name: 'Henry Picard',        country: 'US', era: '1938–1939' },
  'craig-wood':         { name: 'Craig Wood',          country: 'US', era: '1941' },
  'herman-keiser':      { name: 'Herman Keiser',       country: 'US', era: '1946' },
  'claude-harmon':      { name: 'Claude Harmon',       country: 'US', era: '1948' },
  'jack-burke':         { name: 'Jack Burke Jr.',      country: 'US', era: '1956' },
  'doug-ford':          { name: 'Doug Ford',           country: 'US', era: '1955–1957' },
  'art-wall':           { name: 'Art Wall',            country: 'US', era: '1959' },
  'gay-brewer':         { name: 'Gay Brewer',          country: 'US', era: '1967' },
  'bob-goalby':         { name: 'Bob Goalby',          country: 'US', era: '1968' },
  'george-archer':      { name: 'George Archer',       country: 'US', era: '1969' },
  'charles-coody':      { name: 'Charles Coody',       country: 'US', era: '1971' },
  'tommy-aaron':        { name: 'Tommy Aaron',         country: 'US', era: '1973' },
  'tommy-armour':       { name: 'Tommy Armour',        country: 'GB', era: '1927–1931' },
  'olin-dutra':         { name: 'Olin Dutra',          country: 'US', era: '1932–1934' },
  'tom-creavy':         { name: 'Tom Creavy',          country: 'US', era: '1931' },
  'johnny-revolta':     { name: 'Johnny Revolta',      country: 'US', era: '1935' },
  'vic-ghezzi':         { name: 'Vic Ghezzi',          country: 'US', era: '1941' },
  'bob-hamilton':       { name: 'Bob Hamilton',        country: 'US', era: '1944' },
  'jim-ferrier':        { name: 'Jim Ferrier',         country: 'AU', era: '1947' },
  'chandler-harper':    { name: 'Chandler Harper',     country: 'US', era: '1950' },
  'jim-turnesa':        { name: 'Jim Turnesa',         country: 'US', era: '1952' },
  'walter-burkemo':     { name: 'Walter Burkemo',      country: 'US', era: '1953' },
  'chick-harbert':      { name: 'Chick Harbert',       country: 'US', era: '1954' },
  'lionel-hebert':      { name: 'Lionel Hebert',       country: 'US', era: '1957' },
  'dow-finsterwald':    { name: 'Dow Finsterwald',     country: 'US', era: '1958' },
  'bob-rosburg':        { name: 'Bob Rosburg',         country: 'US', era: '1959' },
  'jay-hebert':         { name: 'Jay Hebert',          country: 'US', era: '1960' },
  'horace-rawlins':     { name: 'Horace Rawlins',      country: 'GB', era: '1895' },
  'james-foulis':       { name: 'James Foulis',        country: 'GB', era: '1896' },
  'joe-lloyd':          { name: 'Joe Lloyd',           country: 'GB', era: '1897' },
  'fred-herd':          { name: 'Fred Herd',           country: 'GB', era: '1898' },
  'willie-smith':       { name: 'Willie Smith',        country: 'GB', era: '1899' },
  'laurie-auchterlonie':{ name: 'Laurie Auchterlonie', country: 'GB', era: '1902' },
  'alex-smith':         { name: 'Alex Smith',          country: 'GB', era: '1906–1910' },
  'alec-ross':          { name: 'Alec Ross',           country: 'GB', era: '1907' },
  'fred-mcleod':        { name: 'Fred McLeod',         country: 'GB', era: '1908' },
  'george-sargent':     { name: 'George Sargent',      country: 'GB', era: '1909' },
  'john-mcdermott':     { name: 'John McDermott',      country: 'US', era: '1911–1912' },
  'francis-ouimet':     { name: 'Francis Ouimet',      country: 'US', era: '1913' },
  'ted-ray':            { name: 'Ted Ray',             country: 'GB', era: '1912–1920' },
  'jerome-travers':     { name: 'Jerome Travers',      country: 'US', era: '1915' },
  'chick-evans':        { name: 'Chick Evans',         country: 'US', era: '1916' },
  'jock-hutchison':     { name: 'Jock Hutchison',      country: 'GB', era: '1920–1921' },
  'cyril-walker':       { name: 'Cyril Walker',        country: 'GB', era: '1924' },
  'willie-macfarlane':  { name: 'Willie Macfarlane',   country: 'GB', era: '1925' },
  'johnny-farrell':     { name: 'Johnny Farrell',      country: 'US', era: '1928' },
  'billy-burke':        { name: 'Billy Burke',         country: 'US', era: '1931' },
  'johnny-goodman':     { name: 'Johnny Goodman',      country: 'US', era: '1933' },
  'sam-parks':          { name: 'Sam Parks Jr.',       country: 'US', era: '1935' },
  'tony-manero':        { name: 'Tony Manero',         country: 'US', era: '1936' },
  'lawson-little':      { name: 'Lawson Little',       country: 'US', era: '1940' },
  'lloyd-mangrum':      { name: 'Lloyd Mangrum',       country: 'US', era: '1946' },
  'lew-worsham':        { name: 'Lew Worsham',         country: 'US', era: '1947' },
  'ed-furgol':          { name: 'Ed Furgol',           country: 'US', era: '1954' },
  'jack-fleck':         { name: 'Jack Fleck',          country: 'US', era: '1955' },
  'dick-mayer':         { name: 'Dick Mayer',          country: 'US', era: '1957' },
  'tommy-bolt':         { name: 'Tommy Bolt',          country: 'US', era: '1958' },
  'gene-littler':       { name: 'Gene Littler',        country: 'US', era: '1961' },
  'ken-venturi':        { name: 'Ken Venturi',         country: 'US', era: '1964' },
  'orville-moody':      { name: 'Orville Moody',       country: 'US', era: '1969' },
  'jerry-pate':         { name: 'Jerry Pate',          country: 'US', era: '1976' },
  'andy-north':         { name: 'Andy North',          country: 'US', era: '1978–1985' },
  'lou-graham':         { name: 'Lou Graham',          country: 'US', era: '1975' },
  'tom-kite':           { name: 'Tom Kite',            country: 'US', era: '1992' },
  'lee-janzen':         { name: 'Lee Janzen',          country: 'US', era: '1993–1998' },
  'corey-pavin':        { name: 'Corey Pavin',         country: 'US', era: '1995' },
  'steve-jones':        { name: 'Steve Jones',         country: 'US', era: '1996' },
  'scott-simpson':      { name: 'Scott Simpson',       country: 'US', era: '1987' },
  'george-duncan':      { name: 'George Duncan',       country: 'GB', era: '1920' },
  'arthur-havers':      { name: 'Arthur Havers',       country: 'GB', era: '1923' },
  'alf-perry':          { name: 'Alf Perry',           country: 'GB', era: '1935' },
  'alf-padgham':        { name: 'Alf Padgham',         country: 'GB', era: '1936' },
  'reg-whitcombe':      { name: 'Reg Whitcombe',       country: 'GB', era: '1938' },
  'dick-burton':        { name: 'Dick Burton',         country: 'GB', era: '1939' },
  'fred-daly':          { name: 'Fred Daly',           country: 'GB', era: '1947' },
  'max-faulkner':       { name: 'Max Faulkner',        country: 'GB', era: '1951' },
  'arnaud-massy':       { name: 'Arnaud Massy',        country: 'FR', era: '1907' },
  'jack-white':         { name: 'Jack White',          country: 'GB', era: '1904' },
  'sandy-herd':         { name: 'Sandy Herd',          country: 'GB', era: '1902' },
  'willie-auchterlonie':{ name: 'Willie Auchterlonie', country: 'GB', era: '1893' },
  'hugh-kirkaldy':      { name: 'Hugh Kirkaldy',       country: 'GB', era: '1891' },
  'harold-hilton':      { name: 'Harold Hilton',       country: 'GB', era: '1892–1897' },
  'john-ball':          { name: 'John Ball',           country: 'GB', era: '1890' },
  'willie-park-jr':     { name: 'Willie Park Jr.',     country: 'GB', era: '1887–1889' },
  'jack-burns':         { name: 'Jack Burns',          country: 'GB', era: '1888' },
  'david-brown':        { name: 'David Brown',         country: 'GB', era: '1886' },
  'bob-martin':         { name: 'Bob Martin',          country: 'GB', era: '1876–1885' },
  'willie-fernie':      { name: 'Willie Fernie',       country: 'GB', era: '1883' },
  'jack-simpson':       { name: 'Jack Simpson',        country: 'GB', era: '1884' },
  'mungo-park':         { name: 'Mungo Park',          country: 'GB', era: '1874' },
  'tom-kidd':           { name: 'Tom Kidd',            country: 'GB', era: '1873' },
  'andrew-strath':      { name: 'Andrew Strath',       country: 'GB', era: '1865' },
};

// Build a resolved winners list + career tally
export const ALL_WINS: Win[] = (() => {
  const rows: Win[] = [];
  for (const major of MAJORS) {
    for (const [year, pkey, score, venue, note] of WINNERS[major.key]) {
      rows.push({ major: major.key, year, pkey, score, venue: venue ?? '', note: note ?? '' });
    }
  }
  return rows;
})();

export const PLAYER_STATS: Record<string, PlayerStats> = (() => {
  const stats: Record<string, PlayerStats> = {};
  for (const w of ALL_WINS) {
    const s = stats[w.pkey] || (stats[w.pkey] = { pkey: w.pkey, masters:0, pga:0, usopen:0, open:0, total:0, wins:[] });
    s[w.major]++;
    s.total++;
    s.wins.push(w);
  }
  return stats;
})();

// Top 12 by total, then alpha tiebreak
export const TOP_PLAYERS: PlayerStats[] = Object.values(PLAYER_STATS)
  .sort((a,b) => b.total - a.total || (PLAYERS[a.pkey]?.name||'').localeCompare(PLAYERS[b.pkey]?.name||''))
  .slice(0, 12);

// Country → flag emoji (used only as tiny tag; not as decoration)
export const FLAG: Record<string, string> = {
  US: '🇺🇸', GB: '🇬🇧', ZA: '🇿🇦', ES: '🇪🇸', AU: '🇦🇺', JP: '🇯🇵', KR: '🇰🇷',
  DE: '🇩🇪', IE: '🇮🇪', AR: '🇦🇷', FJ: '🇫🇯', IT: '🇮🇹', SE: '🇸🇪', NZ: '🇳🇿',
  CA: '🇨🇦', FR: '🇫🇷', ZW: '🇿🇼',
};

// Label fallback
export const playerName = (pkey: string): string => PLAYERS[pkey]?.name
  || pkey.split('-').map(s => s[0].toUpperCase()+s.slice(1)).join(' ');
